openapi: 3.0.0
info:
  title: for-serverless-shortener
  version: 1.0.0
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket:             <bucket_name>        # <-- название бакета
        object:             <html_file>          # <-- название html-файла
        presigned_redirect: false
        service_account:    <service_account_id> # <-- ID сервисного аккаунта
      operationId: static
